// src/app/page.js
import React from "react";

export default function HomePage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-purple-200 via-pink-200 to-yellow-100 flex flex-col items-center p-10 text-gray-800">
      <h1 className="text-5xl font-extrabold mb-6 text-center text-purple-800 drop-shadow-lg">
        📚 Scholarship Research Generator
      </h1>

      <p className="text-xl mb-8 max-w-3xl text-center leading-relaxed">
        This site hosts AI-generated research summaries.
        <br />
        Articles are accessible through unique links generated by the browser extension.
      </p>

      <div className="bg-white p-6 rounded-2xl shadow-2xl w-full max-w-3xl">
        <h2 className="text-2xl font-bold mb-4 text-indigo-700">Example Format</h2>
        <pre className="bg-indigo-50 p-4 rounded-lg overflow-x-auto text-indigo-900">
          /details/article-id
        </pre>
      </div>

      <footer className="mt-12 text-gray-600 text-center">
        <p>Made with 💡 AI and ❤️ by your dev</p>
      </footer>
    </main>
  );
}